// IOC / UCI 3-letter codes (used in cycling), label = country name.
// Sorted alphabetically by label.
export const NATIONS: { code: string; label: string }[] = [
  { code: 'ALB', label: 'Albania' },
  { code: 'ALG', label: 'Algeria' },
  { code: 'AND', label: 'Andorra' },
  { code: 'ARG', label: 'Argentina' },
  { code: 'ARM', label: 'Armenia' },
  { code: 'AUS', label: 'Australia' },
  { code: 'AUT', label: 'Austria' },
  { code: 'AZE', label: 'Azerbaijan' },
  { code: 'BLR', label: 'Belarus' },
  { code: 'BEL', label: 'Belgium' },
  { code: 'BIH', label: 'Bosnia and Herzegovina' },
  { code: 'BRA', label: 'Brazil' },
  { code: 'BUL', label: 'Bulgaria' },
  { code: 'CAN', label: 'Canada' },
  { code: 'CHI', label: 'Chile' },
  { code: 'CHN', label: 'China' },
  { code: 'COL', label: 'Colombia' },
  { code: 'CRC', label: 'Costa Rica' },
  { code: 'CRO', label: 'Croatia' },
  { code: 'CUB', label: 'Cuba' },
  { code: 'CYP', label: 'Cyprus' },
  { code: 'CZE', label: 'Czech Republic' },
  { code: 'DEN', label: 'Denmark' },
  { code: 'ECU', label: 'Ecuador' },
  { code: 'EGY', label: 'Egypt' },
  { code: 'ERI', label: 'Eritrea' },
  { code: 'EST', label: 'Estonia' },
  { code: 'ETH', label: 'Ethiopia' },
  { code: 'FIN', label: 'Finland' },
  { code: 'FRA', label: 'France' },
  { code: 'GEO', label: 'Georgia' },
  { code: 'GER', label: 'Germany' },
  { code: 'GBR', label: 'Great Britain' },
  { code: 'GRE', label: 'Greece' },
  { code: 'GUA', label: 'Guatemala' },
  { code: 'HKG', label: 'Hong Kong' },
  { code: 'HUN', label: 'Hungary' },
  { code: 'ISL', label: 'Iceland' },
  { code: 'IND', label: 'India' },
  { code: 'INA', label: 'Indonesia' },
  { code: 'IRI', label: 'Iran' },
  { code: 'IRL', label: 'Ireland' },
  { code: 'ISR', label: 'Israel' },
  { code: 'ITA', label: 'Italy' },
  { code: 'JPN', label: 'Japan' },
  { code: 'KAZ', label: 'Kazakhstan' },
  { code: 'KEN', label: 'Kenya' },
  { code: 'KOR', label: 'Korea, South' },
  { code: 'KGZ', label: 'Kyrgyzstan' },
  { code: 'LAT', label: 'Latvia' },
  { code: 'LIE', label: 'Liechtenstein' },
  { code: 'LTU', label: 'Lithuania' },
  { code: 'LUX', label: 'Luxembourg' },
  { code: 'MKD', label: 'North Macedonia' },
  { code: 'MAS', label: 'Malaysia' },
  { code: 'MLT', label: 'Malta' },
  { code: 'MEX', label: 'Mexico' },
  { code: 'MDA', label: 'Moldova' },
  { code: 'MON', label: 'Monaco' },
  { code: 'MGL', label: 'Mongolia' },
  { code: 'MNE', label: 'Montenegro' },
  { code: 'MAR', label: 'Morocco' },
  { code: 'NAM', label: 'Namibia' },
  { code: 'NED', label: 'Netherlands' },
  { code: 'NZL', label: 'New Zealand' },
  { code: 'NOR', label: 'Norway' },
  { code: 'PAK', label: 'Pakistan' },
  { code: 'PAN', label: 'Panama' },
  { code: 'PAR', label: 'Paraguay' },
  { code: 'PER', label: 'Peru' },
  { code: 'PHI', label: 'Philippines' },
  { code: 'POL', label: 'Poland' },
  { code: 'POR', label: 'Portugal' },
  { code: 'PUR', label: 'Puerto Rico' },
  { code: 'QAT', label: 'Qatar' },
  { code: 'ROU', label: 'Romania' },
  { code: 'RUS', label: 'Russia' },
  { code: 'RWA', label: 'Rwanda' },
  { code: 'SMR', label: 'San Marino' },
  { code: 'KSA', label: 'Saudi Arabia' },
  { code: 'SRB', label: 'Serbia' },
  { code: 'SGP', label: 'Singapore' },
  { code: 'SVK', label: 'Slovakia' },
  { code: 'SLO', label: 'Slovenia' },
  { code: 'RSA', label: 'South Africa' },
  { code: 'ESP', label: 'Spain' },
  { code: 'SWE', label: 'Sweden' },
  { code: 'SUI', label: 'Switzerland' },
  { code: 'TPE', label: 'Taiwan' },
  { code: 'THA', label: 'Thailand' },
  { code: 'TUN', label: 'Tunisia' },
  { code: 'TUR', label: 'Turkey' },
  { code: 'UKR', label: 'Ukraine' },
  { code: 'UAE', label: 'United Arab Emirates' },
  { code: 'USA', label: 'United States' },
  { code: 'URU', label: 'Uruguay' },
  { code: 'UZB', label: 'Uzbekistan' },
  { code: 'VEN', label: 'Venezuela' },
  { code: 'VIE', label: 'Vietnam' },
];
